# Generated by Django 4.2.3 on 2023-07-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songs",
            name="databaseID",
            field=models.IntegerField(default=12312332),
            preserve_default=False,
        ),
    ]
