# Generated by Django 4.2.3 on 2023-07-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_queries_mood_remove_queries_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='query',
        ),
        migrations.AddField(
            model_name='queries',
            name='mood',
            field=models.CharField(choices=[('happy', 'happy'), ('confused', 'confused'), ('proud', 'proud'), ('relaxed', 'relaxed'), ('unamused', 'unameused')], default='happy', max_length=20),
        ),
        migrations.AddField(
            model_name='queries',
            name='period',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='singer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
