# Generated by Django 4.2.3 on 2023-07-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_queries_query_queries_mood_queries_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='period',
        ),
    ]
